// <auto-generated />
using System;
using System.Collections.Generic;
using LegalCaseManagement.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Pgvector;

#nullable disable

namespace LegalCaseManagement.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260730224600_ModeloConsolidado")]
    partial class ModeloConsolidado
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "vector");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("LegalCaseManagement.Domain.Entities.AuditLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Accion")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("accion");

                    b.Property<Guid>("ExpedienteId")
                        .HasColumnType("uuid")
                        .HasColumnName("expediente_id");

                    b.Property<DateTime>("FechaUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_utc");

                    b.Property<string>("HashActual")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("hash_actual");

                    b.Property<string>("HashAnterior")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("hash_anterior");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<Guid>("UsuarioId")
                        .HasColumnType("uuid")
                        .HasColumnName("usuario_id");

                    b.HasKey("Id")
                        .HasName("pk_audit_logs");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix_audit_logs_tenant_id");

                    b.ToTable("audit_logs", (string)null);
                });

            modelBuilder.Entity("LegalCaseManagement.Domain.Entities.Cliente", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("CanalPreferido")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("canal_preferido");

                    b.Property<string>("DniCif")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("dni_cif");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("email");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("nombre");

                    b.Property<string>("Telefono")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("telefono");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.HasKey("Id")
                        .HasName("pk_clientes");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix_clientes_tenant_id");

                    b.ToTable("clientes", (string)null);
                });

            modelBuilder.Entity("LegalCaseManagement.Domain.Entities.DocumentoAdjunto", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("content_type");

                    b.Property<int>("EstadoProcesamiento")
                        .HasColumnType("integer")
                        .HasColumnName("estado_procesamiento");

                    b.Property<Guid>("ExpedienteId")
                        .HasColumnType("uuid")
                        .HasColumnName("expediente_id");

                    b.Property<DateTime?>("FechaProcesado")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_procesado");

                    b.Property<DateTime>("FechaSubida")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_subida");

                    b.Property<string>("NombreArchivo")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("nombre_archivo");

                    b.Property<string>("RutaAlmacenamiento")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("ruta_almacenamiento");

                    b.Property<long>("TamanoBytes")
                        .HasColumnType("bigint")
                        .HasColumnName("tamano_bytes");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<string>("TipoDocumento")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("tipo_documento");

                    b.HasKey("Id")
                        .HasName("pk_documentos_adjuntos");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix_documentos_adjuntos_tenant_id");

                    b.ToTable("documentos_adjuntos", (string)null);
                });

            modelBuilder.Entity("LegalCaseManagement.Domain.Entities.EntidadExtraida", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<double>("Confianza")
                        .HasColumnType("double precision")
                        .HasColumnName("confianza");

                    b.Property<Guid>("DocumentoAdjuntoId")
                        .HasColumnType("uuid")
                        .HasColumnName("documento_adjunto_id");

                    b.Property<int>("Estado")
                        .HasColumnType("integer")
                        .HasColumnName("estado");

                    b.Property<Guid>("ExpedienteId")
                        .HasColumnType("uuid")
                        .HasColumnName("expediente_id");

                    b.Property<Guid>("FragmentoId")
                        .HasColumnType("uuid")
                        .HasColumnName("fragmento_id");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<int>("Tipo")
                        .HasColumnType("integer")
                        .HasColumnName("tipo");

                    b.Property<string>("ValorNormalizado")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("valor_normalizado");

                    b.Property<string>("ValorTexto")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("valor_texto");

                    b.HasKey("Id")
                        .HasName("pk_entidades_extraidas");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix_entidades_extraidas_tenant_id");

                    b.ToTable("entidades_extraidas", (string)null);
                });

            modelBuilder.Entity("LegalCaseManagement.Domain.Entities.EventoCronologia", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<double?>("Confianza")
                        .HasColumnType("double precision")
                        .HasColumnName("confianza");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("descripcion");

                    b.Property<Guid?>("DocumentoAdjuntoId")
                        .HasColumnType("uuid")
                        .HasColumnName("documento_adjunto_id");

                    b.Property<Guid>("ExpedienteId")
                        .HasColumnType("uuid")
                        .HasColumnName("expediente_id");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha");

                    b.Property<Guid?>("FragmentoId")
                        .HasColumnType("uuid")
                        .HasColumnName("fragmento_id");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.HasKey("Id")
                        .HasName("pk_eventos_cronologia");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix_eventos_cronologia_tenant_id");

                    b.ToTable("eventos_cronologia", (string)null);
                });

            modelBuilder.Entity("LegalCaseManagement.Domain.Entities.Expediente", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Cliente")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("cliente");

                    b.Property<int>("Estado")
                        .HasColumnType("integer")
                        .HasColumnName("estado");

                    b.Property<DateTime>("FechaApertura")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_apertura");

                    b.Property<DateTime?>("FechaCierre")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_cierre");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("titulo");

                    b.HasKey("Id")
                        .HasName("pk_expedientes");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix_expedientes_tenant_id");

                    b.ToTable("expedientes", (string)null);
                });

            modelBuilder.Entity("LegalCaseManagement.Domain.Entities.Factura", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Concepto")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("concepto");

                    b.Property<Guid>("ExpedienteId")
                        .HasColumnType("uuid")
                        .HasColumnName("expediente_id");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha");

                    b.Property<decimal>("Importe")
                        .HasColumnType("numeric")
                        .HasColumnName("importe");

                    b.Property<int>("Modo")
                        .HasColumnType("integer")
                        .HasColumnName("modo");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.HasKey("Id")
                        .HasName("pk_facturas");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix_facturas_tenant_id");

                    b.ToTable("facturas", (string)null);
                });

            modelBuilder.Entity("LegalCaseManagement.Domain.Entities.FragmentoDocumento", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("DocumentoAdjuntoId")
                        .HasColumnType("uuid")
                        .HasColumnName("documento_adjunto_id");

                    b.Property<Vector>("Embedding")
                        .HasColumnType("vector(1536)")
                        .HasColumnName("embedding");

                    b.Property<int>("Pagina")
                        .HasColumnType("integer")
                        .HasColumnName("pagina");

                    b.Property<int>("Parrafo")
                        .HasColumnType("integer")
                        .HasColumnName("parrafo");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<string>("TextoFragmento")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("texto_fragmento");

                    b.HasKey("Id")
                        .HasName("pk_fragmentos_documento");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix_fragmentos_documento_tenant_id");

                    b.ToTable("fragmentos_documento", (string)null);
                });

            modelBuilder.Entity("LegalCaseManagement.Domain.Entities.Materia", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("nombre");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.HasKey("Id")
                        .HasName("pk_materias");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix_materias_tenant_id");

                    b.ToTable("materias", (string)null);
                });

            modelBuilder.Entity("LegalCaseManagement.Domain.Entities.ParteContraria", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("ExpedienteId")
                        .HasColumnType("uuid")
                        .HasColumnName("expediente_id");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("nombre");

                    b.Property<string>("RepresentanteLegal")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("representante_legal");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("tipo");

                    b.HasKey("Id")
                        .HasName("pk_partes_contrarias");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix_partes_contrarias_tenant_id");

                    b.ToTable("partes_contrarias", (string)null);
                });

            modelBuilder.Entity("LegalCaseManagement.Domain.Entities.Plazo", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("descripcion");

                    b.PrimitiveCollection<List<int>>("DiasAvisoPrevio")
                        .IsRequired()
                        .HasColumnType("integer[]")
                        .HasColumnName("dias_aviso_previo");

                    b.Property<Guid>("ExpedienteId")
                        .HasColumnType("uuid")
                        .HasColumnName("expediente_id");

                    b.Property<DateTime>("FechaLimite")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_limite");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("tipo");

                    b.HasKey("Id")
                        .HasName("pk_plazos");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix_plazos_tenant_id");

                    b.ToTable("plazos", (string)null);
                });

            modelBuilder.Entity("LegalCaseManagement.Domain.Entities.ProvisionDeFondos", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("Aplicada")
                        .HasColumnType("boolean")
                        .HasColumnName("aplicada");

                    b.Property<Guid>("ExpedienteId")
                        .HasColumnType("uuid")
                        .HasColumnName("expediente_id");

                    b.Property<DateTime>("FechaSolicitud")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_solicitud");

                    b.Property<decimal>("Importe")
                        .HasColumnType("numeric")
                        .HasColumnName("importe");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.HasKey("Id")
                        .HasName("pk_provisiones_de_fondos");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix_provisiones_de_fondos_tenant_id");

                    b.ToTable("provisiones_de_fondos", (string)null);
                });

            modelBuilder.Entity("LegalCaseManagement.Domain.Entities.Tenant", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("nombre");

                    b.Property<string>("Plan")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("plan");

                    b.HasKey("Id")
                        .HasName("pk_tenants");

                    b.ToTable("tenants", (string)null);
                });

            modelBuilder.Entity("LegalCaseManagement.Domain.Entities.Usuario", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("email");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("password_hash");

                    b.Property<int>("Rol")
                        .HasColumnType("integer")
                        .HasColumnName("rol");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.HasKey("Id")
                        .HasName("pk_usuarios");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix_usuarios_tenant_id");

                    b.ToTable("usuarios", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
